apiVersion: v1
kind: Service
metadata:
  name: {{ include "postkeys.fullname" . }}
  labels:
    {{- include "postkeys.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    {{- include "postkeys.selectorLabels" . | nindent 4 }}
    {{- if .Values.leaderElection.enabled }}
    postkeys/role: leader
    {{- end }}
